### ISSUE TITLE
gatsby改造

### ISSUE THREAD

**Issue by neoddish** [Plothis/gradict-charts-doc#4]
https://www.yuque.com/plothis/gradict_dev/ovf5iq

这个repo能用么？还是整合到一个完整的网站repo？ @BBSQQ

**Comment by BBSQQ** [comment]
看起来是可以用的，可以改个名字

**Comment by jiazhewang** [comment]
如果能下拉起一个页面，就可以组织大家按照样式来参与补全md了

**Comment by BBSQQ** [comment]
> 如果能下拉起一个页面，就可以组织大家按照样式来参与补全md了

好的，我近期搭个框架，列个待办
